#!/bin/bash
path="/usr/share/navale/navale.py"
echo "Starting Navale..."
echo "Path: $path"
echo "Dev: $1"
echo "----------------------"

if [ $1 == "--dev" ]; then
    python $path --webEngineArgs --remote-debugging-port=3030
else
    python $path
fi
